# Generated by Django 5.2.5 on 2025-11-30 01:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inscripción')),
                ('estado', models.CharField(choices=[('CURSANDO', 'Cursando'), ('REGULAR', 'Regular'), ('APROBADO', 'Aprobado'), ('DESAPROBADO', 'Desaprobado')], default='CURSANDO', max_length=15, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-fecha_inscripcion'],
            },
        ),
    ]
