# Generated by Django 5.2.5 on 2025-11-30 01:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuelas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(7, 'El DNI debe tener al menos 7 dígitos'), django.core.validators.RegexValidator('^\\d{7,8}$', 'El DNI debe contener entre 7 y 8 dígitos numéricos')], verbose_name='DNI')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('legajo', models.CharField(help_text='Formato: {año}{codigo_carrera}{nro_secuencial}', max_length=20, unique=True, verbose_name='Legajo')),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='escuelas.carrera', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
