# Generated by Django 5.2.5 on 2025-11-30 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(7, 'El DNI debe tener al menos 7 dígitos'), django.core.validators.RegexValidator('^\\d{7,12}$', 'El DNI debe contener entre 7 y 12 dígitos numéricos')], verbose_name='DNI'),
        ),
    ]
