# Generated by Django 5.2.5 on 2025-08-19 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único de la carrera en todo el sistema', max_length=200, unique=True, verbose_name='Nombre de la Carrera')),
                ('codigo', models.CharField(help_text='Código único identificatorio (ej: ING-SIS, PROF-MAT)', max_length=20, unique=True, verbose_name='Código de Carrera')),
                ('duracion_anos', models.PositiveIntegerField(default=4, help_text='Duración nominal de la carrera en años', verbose_name='Duración en Años')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la carrera está disponible para nuevas inscripciones', verbose_name='Carrera Activa')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la carrera y perfil profesional', verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['codigo'], name='escuelas_ca_codigo_92c370_idx'), models.Index(fields=['activa'], name='escuelas_ca_activa_b95aa5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la materia (único por carrera)', max_length=200, verbose_name='Nombre de la Materia')),
                ('codigo', models.CharField(help_text='Código identificatorio (ej: MAT101, FIS201)', max_length=20, verbose_name='Código de Materia')),
                ('cupo_maximo', models.PositiveIntegerField(help_text='Número máximo de estudiantes que pueden cursar la materia', verbose_name='Cupo Máximo')),
                ('año_carrera', models.PositiveIntegerField(default=1, help_text='Año del plan de estudios en que se cursa (1, 2, 3, etc.)', verbose_name='Año de la Carrera')),
                ('cuatrimestre', models.PositiveIntegerField(choices=[(1, '1° Cuatrimestre'), (2, '2° Cuatrimestre'), (0, 'Anual')], default=1, verbose_name='Cuatrimestre')),
                ('horas_semanales', models.PositiveIntegerField(default=4, help_text='Cantidad de horas de clase por semana', verbose_name='Horas Semanales')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la materia está disponible para cursar', verbose_name='Materia Activa')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la materia y sus objetivos', verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('carrera', models.ForeignKey(help_text='Carrera a la que pertenece esta materia', on_delete=django.db.models.deletion.PROTECT, related_name='materias', to='escuelas.carrera', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['carrera__nombre', 'año_carrera', 'cuatrimestre', 'nombre'],
                'indexes': [models.Index(fields=['carrera', 'año_carrera'], name='escuelas_ma_carrera_705f5c_idx'), models.Index(fields=['activa'], name='escuelas_ma_activa_bf099f_idx'), models.Index(fields=['codigo'], name='escuelas_ma_codigo_7ea803_idx')],
                'constraints': [models.UniqueConstraint(fields=('carrera', 'nombre'), name='unique_materia_por_carrera', violation_error_message='Ya existe una materia con este nombre en la carrera seleccionada.'), models.UniqueConstraint(fields=('carrera', 'codigo'), name='unique_codigo_por_carrera', violation_error_message='Ya existe una materia con este código en la carrera seleccionada.')],
            },
        ),
    ]
