# Generated by Django 5.2.5 on 2025-11-30 01:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de la carrera (ej: ING, LIC, TEC)', max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('duracion_años', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duración en años')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('año_carrera', models.PositiveIntegerField(help_text='Año de la carrera en el que se cursa esta materia', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Año de la carrera')),
                ('cupo_maximo', models.PositiveIntegerField(help_text='Cantidad máxima de alumnos que pueden inscribirse', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cupo máximo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materias', to='escuelas.carrera', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['carrera', 'año_carrera', 'nombre'],
                'unique_together': {('carrera', 'codigo')},
            },
        ),
    ]
