# Generated by Django 5.2.5 on 2025-11-30 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materia',
            unique_together={('carrera', 'codigo'), ('carrera', 'nombre')},
        ),
    ]
